### ISSUE TITLE
Add a layer between api and action creators for parsing payload

### ISSUE THREAD

**Issue by AlbertLucianto** [Kindev/fundraisee-web#6]
## Motivation

Just sharing a painful experience working with python backend.

Because python uses `snake_case` and javascript uses `camelCase` as naming convention, sometimes `snake_case` from api responses can clutter up the frontend codes if not carefully handled. A similar case may also happen while sending api payload to backend.

Would it be nice to abstract away the naming convention by implementing an object transformer?

For example in sending some state,
```js
const state = {
  someInternalState: {
    someKey: 'some value',
  },
};
```

will be transformed before sending into
```js
const payload = {
  some_internal_state: {
    some_key: 'some value',
  },
};
```

and vice versa.

_p.s. I have the code for parsing back and forth_ :sweat_smile:

**Comment by michjk** [comment]
Do you think there is a chance that developer may not aware when to use camel case and snake case even though we decide already to use either cases for schema data?

**Comment by endiliey** [comment]
Should be pretty simple implementation with lodash. Just make sure to add test on the transformer function.

Are you going to write a redux middleware for it ?
Then user dont have to call the object transformer function normally

Or they can always call it manually too

**Comment by AlbertLucianto** [comment]
@michjk it’s not impossible that one accidentally inserts deeply nested api response to state.

@endiliey one way is to create an api base class which one method wraps axios. This class by default will set some common config (e.g. headers, possibly parsing payload before send). All apis should then extend this class.

But probably it’s not necessary atm. I’m closing this.
